### ISSUE TITLE
Build out CI jobs

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#12]
Determine the CI jobs that are needed for this project and configure them.

More info needed on the scope of this issue.

**Comment by limed** [comment]
Our CI system needs to support this: https://github.com/nubisproject/nubis-ci/issues/625

**Comment by mgreensmith** [comment]
- Jenkins multi-branch pipeline
- Jenkins runs unit tests on any branch push (not PRS, and this workflow is unused for anything but master)
- on master push, Jenkins runs unit tests, and then builds containers and pushes to quay.
- merging master into `stage-push` branch pushes those containers to a staging env
- merging master into `prod-push` branch pushes those containers to a staging env
- merging master into `standby-push` branch pushes containers to the DR/standby cluster
- run selenium tests against staging after deploy, some are unsafe against prod
- there's a smoke test suite ("headless suite") of curl checks that run againt staging after each deploy

MozMEAO is moving to:
- Jenkins commits some k8s YAML to a config repo
- a k8s operator in cluster polls the config repo and hydrates the YAML into the cluster

**Comment by jwhitlock** [comment]
Here's the gross details, with links.

Our [deployment process](https://kuma.readthedocs.io/en/latest/deploy.html) is a a lot of pushing branches, with a Jenkins multi-branch pipeline taking actions based on the branch. There's a multi branch pipeline for [mozilla/kuma](https://github.com/mozilla/kuma), the Python engine, and for [mdn/kumascript](https://github.com/mdn/kumascript), the node.js script renderer.

For kuma, Jenkins looks at [Jenkinsfile](https://github.com/mozilla/kuma/blob/master/Jenkinsfile). It does some stuff for every branch, and then looks for a branch-specific file for custom behavior. If it doesn't find one, it runs [default.groovy](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/default.groovy), which runs tests and pushes images tagged with the abbreviated git commit.

The current special branches:
* ``master`` - Loads [master.groovy](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/master.groovy), which pushes images tagged with both the abbreviated git commit and ``latest``.
* ``standby-push`` - [stage-push.yml](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/stage-push.yml) configures [push.groovy](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/push.groovy) to runs the steps to deploy an image to production:
  - Tell IRC a deploy has started
  - Check the desired image is on [quay.io](https://quay.io/repository/mozmar/kuma?tab=tags)
  - Check out latest [infra](https://github.com/mdn/infra)
  - Migrate the database
  - Execute a Kubernetes rollout
  - Watch for the rollout to complete
  The image is based on the commit hash of the branch, so it is important that ``standby-push`` matches a branch that was previously built, like ``master``.
* ``prod-push`` - [prod-push.yml](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/prod-push.yml) does the same as ``stage-push``, but for production.
* ``stage-push`` - [standby-push.yml](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/standby-push.yml) does the same as ``stage-push``, but for the standby cluster in Europe.
* ``stage-integration-tests`` - [stage-integration-tests.yml](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/stage-integration-tests.yml) configures [integration-tests.groovy](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/integration-tests.groovy) to run [Selenium tests](https://github.com/mozilla/kuma/tree/master/tests/functional) for Chrome and Firefox, as well as some [headless tests](https://github.com/mozilla/kuma/tree/master/tests/headless) that make network requests without a browser.  The branch controls what tests are run.
* ``prod-integration-tests``- Same as ``stage-integration-tests``, but run against production.

Jenkins runs _something_ for any branch in [mozilla/kuma](https://github.com/mozilla/kuma). We don't usually push in-work branches to that repository, unless we want to run them on staging, or we are writing new integration tests. Most work is done in our own repos, like [jwhitlock/kuma](https://github.com/jwhitlock/kuma), and then merged as part of the pull request process. In addition, it's potentially dangerous to bring random branches onto mozilla/kuma, since it will execute on Jenkins.

The Jenkins pipeline / workflow for Kumascript is based on a single [Jenkinsfile](https://github.com/mdn/kumascript/blob/master/Jenkinsfile) that does all the work.  There is special code for the ``master``, ``stage-push``, ``prod-push``, and ``standby-push`` branches, and the default is to run tests.

**Comment by mgreensmith** [comment]
#15, #41, #42, #43

**Comment by limed** [comment]
Done
