### ISSUE TITLE
Publish docker images from CI server

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#15]
Build docker images and push them to the repository from the CI server.  The MozMEAO Jenkins will continue building and pushing its own images. 

* MozMeao repository - https://quay.io/repository/mozmar
* IT Cloud repository - https://hub.docker.com/u/mdnwebdocs

| Image | MozMEAO name | IT Cloud name |
| -- | -- | -- |
| kuma_base | quay.io/mozmar/kuma_base | mdnwebdocs/kuma_base |
| kuma | quay.io/mozmar/kuma | mdnwebdocs/kuma |
| kumascript | quay.io/mozmar/kumascript | mdnwebdocs/kumascript |

Tasks:

* [ ] Allow name to be configured from environment (devs)
* [ ] Configure kuma pipeline to use IT Cloud name (IT)
* [ ] Configure kumascript pipeline to use IT Cloud name (IT)
* [ ] Determine credentials needed to push images (devs)
* [ ] Provision and install push credentials on IT Cloud CI server (IT and devs)
* [ ] Push kuma_base and kuma images from kuma pipeline (IT and devs)
* [ ] Push kumascript images from kumascript pipeline (IT and devs)

**Comment by jwhitlock** [comment]
I'd support changing the title to "Publish docker images from CI server" so that it doesn't sound like quay.io is the requirement.

**Comment by mgreensmith** [comment]
- Set up an account at Dockerhub or Quay
   - Configure image build jobs to ship to the new location.

**Comment by jwhitlock** [comment]
Let's try Docker Hub. I've started a new org, nothing to see yet.

https://hub.docker.com/u/mdnwebdocs/

I tested out the automated build feature for Docker Hub. To work with our repository setup I needed to [override the build step](https://docs.docker.com/docker-cloud/builds/advanced/), so that the build folder would be the root folder, not ``docker/images/kuma_base/`` where the ``Dockerfile`` is. Even more would be needed to get the kumascript build working. It took about 15 minutes from when the commit was made to when the build completed. Additional work will be needed to push with the SHA hash of the commit as the tag number (but might be easy to do with a ``post_push`` hook.

But, successfully created a kuma_base image with a dockerhub automated build:

https://hub.docker.com/r/jwhitlock/kuma_base/
https://github.com/jwhitlock/kuma/blob/09536627ec017baac7cb926eb31efeadf96a0187/docker/images/kuma_base/hooks/build

**Comment by limed** [comment]
We made this worked and its done, deprecating this repo
