### ISSUE TITLE
Populate anonymized dataset into staging Mysql

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#22]
Load the anonymized database into the existing stage MySQL instance.

Could be from a snapshot if @metadave has one.

**Comment by escattone** [comment]
This is done. I was able to configure some permissions within the MozMEAO AWS account such that I could see its RDS snapshots from the IT AWS account. I decided not to use snapshots since they cannot be loaded into an existing RDS instance, but require the creation of a new RDS instance. Instead I dumped the existing DB from the stage RDS instance within the MozMEAO AWS account and loaded it into the stage RDS instance within the IT AWS account.
