### ISSUE TITLE
Configure sso dashboard access

### ISSUE THREAD

**Issue by tinnightcap** [mozilla-itcloud/mdn-migration-project#32]
Need ldap group name that all mdn folks are in to grant access to nubis sso dashboard.

**Comment by mgreensmith** [comment]
`team_mdn` is the LDAP group, we need a servicenow request to add folks to it.

**Comment by jwhitlock** [comment]
Opened ticket INC0025294 in ServiceNow. It's not clear if this is the right place 🙂 .

**Comment by jwhitlock** [comment]
We are now are in the ``team_mdn`` LDAP group, and I'm tagged as the owner. I still get a 401 Unauthorized from the SSO dashboard, so there are probably follow-on actions, or the LDAP changes need to propagate.

**Comment by mgreensmith** [comment]
Ah, yeah, so we recently learned that LDAP groups only propagate to Auth0 when you explicitly log into an new Auth0 session. So A first troubleshooting step would be to force log out and log back in to Auth0.

(discussion here: https://github.com/mozilla-itcloud/datateam-project/issues/12)

**Comment by jwhitlock** [comment]
I deleted my cookie on the SSO domain, and visited https://auth.mozilla.auth0.com/v2/logout?federated, and came back to the SSO site. I went through login, but still 401.

**Comment by tinnightcap** [comment]
I am checking in to see if you are still having issues with access? If so can you please visit 
https://sso.mozilla.com/logout

You will need to actually log out of sso because it only syncs your ldap groups on a new login. Everything was set up last week and should be working now. If you continue to have issues let us know.

**Comment by jwhitlock** [comment]
Going to https://sso.mozilla.com/logout directly leads to an Internal Server Error 😕 .

Log out works if I go to https://sso.mozilla.com/, then select Logout from the profile menu, going to a page that says "Log Out Success". I'm prompted for username and password when I then go to https://sso.mozilla.com/.

However, https://sso.mozilla.com/dashboard does not appear to have a relevant entry for this work (I could be wrong, the icons/names don't communicate what the service is for), and I still get a 401 at https://sso.core.us-west-2.mozilla-mdn.nubis.allizom.org

**Comment by mgreensmith** [comment]
@jwhitlock Could you please paste a gist of the output of https://sso.core.us-west-2.mozilla-mdn.nubis.allizom.org/sso?info=json for you? You should be able to get there even though you see a `401` on the root of the domain.

We want to confirm that you're not getting the correct group memberships propagated from LDAP > Auth0 on login.

**Comment by jwhitlock** [comment]
I get a 401 Unauthorized for [/sso?info=json](https://sso.core.us-west-2.mozilla-mdn.nubis.allizom.org/sso?info=json) as well.

**Comment by mgreensmith** [comment]
Today I learned:

The index page at  https://sso.core.us-west-2.mozilla-mdn.nubis.allizom.org does the _authentication_ dance with Auth0, so if you've been logged out of Auth0, you need to fetch that page before you can visit the SSO info page at `/sso?info=json`.  You'll get a `401` on the index if you're authenticated but not authorized to view the dashboard.

@jwhitlock did this dance with me today, saw a `401` on the index page (as expected if his group memberships weren't propagating to Auth0), and could then successfully fetch the `/sso` info page (because we was authenticated).

Here's his JSON from `/sso`: https://gist.github.com/jwhitlock/f63f4705a490a25884ef788538925897 

The bad news is that Auth0 does see that he is a member of `team_mdn` group (it's included in the output), so he should have been able to see the index page.

So there is some other reason why he's getting a `401`.

**Comment by tinnightcap** [comment]
@jwhitlock can you try one more time. We found a typo in our config file which has been addressed and pushed to the account. In fact everyone in the team_mdn group should be unblocked now.

**Comment by jwhitlock** [comment]
I'm able to login and view the dashboard. Success! 

@escattone, @jgmize, @metadave - can you try to access the dashboard? You may need to log out of SSO to get the LDAP group applied, see the discussion on this issue.

**Comment by metadave** [comment]
I'm able to see https://sso.core.us-west-2.mozilla-mdn.nubis.allizom.org/

**Comment by escattone** [comment]
https://sso.core.us-west-2.mozilla-mdn.nubis.allizom.org/ Works for me, thanks!
